name: Deploy to EC2 (simple)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up SSH agent with deploy key
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Add EC2 to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Rsync to EC2
      run: |
        rsync -avz --delete --exclude='.git' --exclude='.github' ./ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }}:${{ secrets.REMOTE_PATH }}
      env:
        RSYNC_RSH: "ssh -o StrictHostKeyChecking=yes -p ${{ secrets.EC2_PORT || '22' }}"

    - name: Reload nginx on EC2
      run: |
        ssh -o StrictHostKeyChecking=yes -p ${{ secrets.EC2_PORT || '22' }} \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "sudo systemctl reload nginx || sudo systemctl restart nginx"
