name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Copy files to EC2 and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/myapp || git clone https://github.com/${{ github.repository }} myapp
            cd myapp
            git pull origin main

            # For static site (index.html)
            sudo cp index.html /var/www/html/index.html

            # OR for Node.js app:
            # npm install
            # pm2 restart all || pm2 start app.js

            echo "Deployment successful!"
